// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt time.Time
	UserID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
